/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppValidationRouteImport } from './routes/app.validation'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppHeatmapRouteImport } from './routes/app.heatmap'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppApprovalsRouteImport } from './routes/app.approvals'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppOperationsIndexRouteImport } from './routes/app.operations.index'
import { Route as AppOperationsNewRouteImport } from './routes/app.operations.new'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminSettingsRouteImport } from './routes/app.admin.settings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppValidationRoute = AppValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppHeatmapRoute = AppHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsIndexRoute = AppOperationsIndexRouteImport.update({
  id: '/operations/',
  path: '/operations/',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsNewRoute = AppOperationsNewRouteImport.update({
  id: '/operations/new',
  path: '/operations/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/heatmap': typeof AppHeatmapRoute
  '/app/reports': typeof AppReportsRoute
  '/app/validation': typeof AppValidationRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/operations/new': typeof AppOperationsNewRoute
  '/app/operations/': typeof AppOperationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/heatmap': typeof AppHeatmapRoute
  '/app/reports': typeof AppReportsRoute
  '/app/validation': typeof AppValidationRoute
  '/app': typeof AppIndexRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/operations/new': typeof AppOperationsNewRoute
  '/app/operations': typeof AppOperationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/heatmap': typeof AppHeatmapRoute
  '/app/reports': typeof AppReportsRoute
  '/app/validation': typeof AppValidationRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/operations/new': typeof AppOperationsNewRoute
  '/app/operations/': typeof AppOperationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/alerts'
    | '/app/approvals'
    | '/app/audit'
    | '/app/heatmap'
    | '/app/reports'
    | '/app/validation'
    | '/app/'
    | '/app/admin/settings'
    | '/app/admin/users'
    | '/app/operations/new'
    | '/app/operations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/alerts'
    | '/app/approvals'
    | '/app/audit'
    | '/app/heatmap'
    | '/app/reports'
    | '/app/validation'
    | '/app'
    | '/app/admin/settings'
    | '/app/admin/users'
    | '/app/operations/new'
    | '/app/operations'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/alerts'
    | '/app/approvals'
    | '/app/audit'
    | '/app/heatmap'
    | '/app/reports'
    | '/app/validation'
    | '/app/'
    | '/app/admin/settings'
    | '/app/admin/users'
    | '/app/operations/new'
    | '/app/operations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/validation': {
      id: '/app/validation'
      path: '/validation'
      fullPath: '/app/validation'
      preLoaderRoute: typeof AppValidationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/heatmap': {
      id: '/app/heatmap'
      path: '/heatmap'
      fullPath: '/app/heatmap'
      preLoaderRoute: typeof AppHeatmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operations/': {
      id: '/app/operations/'
      path: '/operations'
      fullPath: '/app/operations/'
      preLoaderRoute: typeof AppOperationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operations/new': {
      id: '/app/operations/new'
      path: '/operations/new'
      fullPath: '/app/operations/new'
      preLoaderRoute: typeof AppOperationsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/admin/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppHeatmapRoute: typeof AppHeatmapRoute
  AppReportsRoute: typeof AppReportsRoute
  AppValidationRoute: typeof AppValidationRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppOperationsNewRoute: typeof AppOperationsNewRoute
  AppOperationsIndexRoute: typeof AppOperationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppAuditRoute: AppAuditRoute,
  AppHeatmapRoute: AppHeatmapRoute,
  AppReportsRoute: AppReportsRoute,
  AppValidationRoute: AppValidationRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppOperationsNewRoute: AppOperationsNewRoute,
  AppOperationsIndexRoute: AppOperationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
